import type { FibFact } from "./types";

const FACTS: FibFact[] = [
  // ── Animals ─────────────────────────────────────────────────────────
  { id: "ani-01", category: "animals", text: "A group of flamingos is called a ___", answer: "flamboyance" },
  { id: "ani-02", category: "animals", text: "The heart of a ___ is located in its head", answer: "shrimp" },
  { id: "ani-03", category: "animals", text: "Cows have best friends and get ___ when they are separated", answer: "stressed" },
  { id: "ani-04", category: "animals", text: "A snail can sleep for up to ___ years", answer: "three" },
  { id: "ani-05", category: "animals", text: "Octopuses have ___ hearts", answer: "three" },
  { id: "ani-06", category: "animals", text: "A group of porcupines is called a ___", answer: "prickle" },
  { id: "ani-07", category: "animals", text: "Dolphins sleep with one ___ open", answer: "eye" },
  { id: "ani-08", category: "animals", text: "The fingerprints of a ___ are virtually indistinguishable from those of a human", answer: "koala" },
  { id: "ani-09", category: "animals", text: "Butterflies taste with their ___", answer: "feet" },
  { id: "ani-10", category: "animals", text: "A ___ can hold its breath for up to 40 minutes underwater", answer: "sloth" },
  { id: "ani-11", category: "animals", text: "Sea otters hold ___ while they sleep so they don't drift apart", answer: "hands" },
  { id: "ani-12", category: "animals", text: "Elephants are the only animals that can't ___", answer: "jump" },
  { id: "ani-13", category: "animals", text: "A group of owls is called a ___", answer: "parliament" },
  { id: "ani-14", category: "animals", text: "Cats have over ___ vocalizations, while dogs only have about 10", answer: "100" },
  { id: "ani-15", category: "animals", text: "Wombat poop is shaped like a ___", answer: "cube" },
  { id: "ani-16", category: "animals", text: "A ___ can rotate its head nearly 270 degrees", answer: "owl" },
  { id: "ani-17", category: "animals", text: "The tongue of a blue whale weighs as much as a ___", answer: "elephant" },
  { id: "ani-18", category: "animals", text: "Rats ___ when they're tickled", answer: "laugh" },

  // ── History ─────────────────────────────────────────────────────────
  { id: "his-01", category: "history", text: "Cleopatra lived closer in time to the ___ than to the building of the Great Pyramid", answer: "Moon landing" },
  { id: "his-02", category: "history", text: "In ancient Rome, ___ was used as a mouthwash", answer: "urine" },
  { id: "his-03", category: "history", text: "Napoleon was once attacked by a horde of ___", answer: "rabbits" },
  { id: "his-04", category: "history", text: "The shortest war in history lasted ___ minutes", answer: "38" },
  { id: "his-05", category: "history", text: "In medieval times, ___ were put on trial and could be sentenced for crimes", answer: "animals" },
  { id: "his-06", category: "history", text: "Ancient Egyptians used ___ as pillows", answer: "stones" },
  { id: "his-07", category: "history", text: "The Aztecs used ___ beans as currency", answer: "cocoa" },
  { id: "his-08", category: "history", text: "Vikings used the bones of slain ___ to make their drinking vessels", answer: "animals" },
  { id: "his-09", category: "history", text: "In 1932, Australia lost a war against ___", answer: "emus" },
  { id: "his-10", category: "history", text: "Ketchup was once sold as ___", answer: "medicine" },
  { id: "his-11", category: "history", text: "Abraham Lincoln was a champion ___", answer: "wrestler" },
  { id: "his-12", category: "history", text: "Oxford University is older than the ___ Empire", answer: "Aztec" },
  { id: "his-13", category: "history", text: "Ancient Romans used crushed ___ as toothpaste", answer: "mouse brains" },
  { id: "his-14", category: "history", text: "In 1518, a ___ plague struck Strasbourg where people danced uncontrollably for days", answer: "dancing" },
  { id: "his-15", category: "history", text: "The Great Wall of China was held together by a mortar made from ___", answer: "sticky rice" },

  // ── Science ─────────────────────────────────────────────────────────
  { id: "sci-01", category: "science", text: "Hot water freezes ___ than cold water under certain conditions", answer: "faster" },
  { id: "sci-02", category: "science", text: "A teaspoon of a neutron star would weigh about ___ billion tons", answer: "six" },
  { id: "sci-03", category: "science", text: "Bananas are naturally ___", answer: "radioactive" },
  { id: "sci-04", category: "science", text: "There are more trees on Earth than ___ in the Milky Way", answer: "stars" },
  { id: "sci-05", category: "science", text: "Honey never ___", answer: "expires" },
  { id: "sci-06", category: "science", text: "The human body contains enough ___ to make about 900 pencils", answer: "carbon" },
  { id: "sci-07", category: "science", text: "Lightning is ___ times hotter than the surface of the Sun", answer: "five" },
  { id: "sci-08", category: "science", text: "Glass is technically a ___", answer: "liquid" },
  { id: "sci-09", category: "science", text: "Venus is the only planet that spins ___", answer: "clockwise" },
  { id: "sci-10", category: "science", text: "A cloud can weigh more than a million ___", answer: "pounds" },
  { id: "sci-11", category: "science", text: "Sound travels about ___ times faster in water than in air", answer: "four" },
  { id: "sci-12", category: "science", text: "If you could fold a piece of paper 42 times, it would reach the ___", answer: "Moon" },
  { id: "sci-13", category: "science", text: "The human nose can detect over ___ trillion distinct scents", answer: "one" },
  { id: "sci-14", category: "science", text: "A day on ___ is longer than its year", answer: "Venus" },
  { id: "sci-15", category: "science", text: "Sharks have been on Earth longer than ___", answer: "trees" },

  // ── Food ────────────────────────────────────────────────────────────
  { id: "food-01", category: "food", text: "Peanuts are not nuts — they are ___", answer: "legumes" },
  { id: "food-02", category: "food", text: "Strawberries are not technically ___", answer: "berries" },
  { id: "food-03", category: "food", text: "The most stolen food in the world is ___", answer: "cheese" },
  { id: "food-04", category: "food", text: "Apples float in water because they are 25% ___", answer: "air" },
  { id: "food-05", category: "food", text: "Ketchup was originally made from ___", answer: "mushrooms" },
  { id: "food-06", category: "food", text: "Crackers have holes in them to prevent ___", answer: "air bubbles" },
  { id: "food-07", category: "food", text: "The world's most expensive spice by weight is ___", answer: "saffron" },
  { id: "food-08", category: "food", text: "Carrots were originally ___", answer: "purple" },
  { id: "food-09", category: "food", text: "White chocolate isn't technically ___", answer: "chocolate" },
  { id: "food-10", category: "food", text: "Cashews grow on the bottom of a ___", answer: "fruit" },
  { id: "food-11", category: "food", text: "Astronauts cannot ___ in space, so they squeeze food into their mouths", answer: "burp" },
  { id: "food-12", category: "food", text: "Nutmeg is a ___", answer: "hallucinogen" },
  { id: "food-13", category: "food", text: "Ranch dressing is dyed with ___ dioxide, which is also used in sunscreen", answer: "titanium" },
  { id: "food-14", category: "food", text: "Grapes will ___ if you put them in a microwave", answer: "explode" },
  { id: "food-15", category: "food", text: "Spam is short for ___", answer: "spiced ham" },

  // ── Geography ───────────────────────────────────────────────────────
  { id: "geo-01", category: "geography", text: "Russia has a larger surface area than ___", answer: "Pluto" },
  { id: "geo-02", category: "geography", text: "Canada has more ___ than the rest of the world combined", answer: "lakes" },
  { id: "geo-03", category: "geography", text: "There is a town in Norway called ___", answer: "Hell" },
  { id: "geo-04", category: "geography", text: "Africa is the only continent in all four ___", answer: "hemispheres" },
  { id: "geo-05", category: "geography", text: "More people live in ___ than in the entire Western Hemisphere", answer: "Bangladesh" },
  { id: "geo-06", category: "geography", text: "The Sahara Desert is roughly the same size as ___", answer: "the United States" },
  { id: "geo-07", category: "geography", text: "There are ___ countries in the world that are completely surrounded by one other country", answer: "three" },
  { id: "geo-08", category: "geography", text: "The Dead Sea is so salty you can ___ on its surface without trying", answer: "float" },
  { id: "geo-09", category: "geography", text: "Mount Everest grows approximately ___ each year", answer: "4 millimeters" },
  { id: "geo-10", category: "geography", text: "The deepest point in the ocean is deeper than Mount Everest is ___", answer: "tall" },
  { id: "geo-11", category: "geography", text: "Istanbul is the only city in the world located on two ___", answer: "continents" },
  { id: "geo-12", category: "geography", text: "The country with the most time zones is ___", answer: "France" },
  { id: "geo-13", category: "geography", text: "Alaska is simultaneously the most northern, western, and ___ state in the US", answer: "eastern" },
  { id: "geo-14", category: "geography", text: "The shortest place name in the world is ___, a village in France", answer: "Y" },
  { id: "geo-15", category: "geography", text: "There's a city in Turkey called ___", answer: "Batman" },

  // ── Pop Culture ─────────────────────────────────────────────────────
  { id: "pop-01", category: "pop culture", text: "The Monopoly mascot's name is ___", answer: "Rich Uncle Pennybags" },
  { id: "pop-02", category: "pop culture", text: "Mario's original name was ___", answer: "Jumpman" },
  { id: "pop-03", category: "pop culture", text: "The color of the ___ in Star Wars was originally going to be blue", answer: "lightsaber" },
  { id: "pop-04", category: "pop culture", text: "Mickey Mouse's original name was ___", answer: "Mortimer" },
  { id: "pop-05", category: "pop culture", text: "The inventor of the Pringles can is buried in a ___", answer: "Pringles can" },
  { id: "pop-06", category: "pop culture", text: "Barbie's full name is Barbara ___ Roberts", answer: "Millicent" },
  { id: "pop-07", category: "pop culture", text: "The Flintstones was the first cartoon to show a couple in ___ on TV", answer: "bed together" },
  { id: "pop-08", category: "pop culture", text: "Pac-Man was originally called ___", answer: "Puck Man" },
  { id: "pop-09", category: "pop culture", text: "The hashtag symbol is technically called an ___", answer: "octothorpe" },
  { id: "pop-10", category: "pop culture", text: "The word '___ ' was added to the dictionary because of the Simpsons", answer: "D'oh" },
  { id: "pop-11", category: "pop culture", text: "Yoda was originally going to be played by a trained ___", answer: "monkey" },
  { id: "pop-12", category: "pop culture", text: "The first item sold on eBay was a broken ___", answer: "laser pointer" },
  { id: "pop-13", category: "pop culture", text: "Mr. T's real first name is ___", answer: "Laurence" },
  { id: "pop-14", category: "pop culture", text: "Nintendo originally sold ___", answer: "playing cards" },
  { id: "pop-15", category: "pop culture", text: "The first YouTube video ever uploaded was about a visit to the ___", answer: "zoo" },

  // ── Language ────────────────────────────────────────────────────────
  { id: "lang-01", category: "language", text: "The dot over the letters 'i' and 'j' is called a ___", answer: "tittle" },
  { id: "lang-02", category: "language", text: "The shortest complete sentence in English is ___", answer: "Go" },
  { id: "lang-03", category: "language", text: "The word 'queue' is just the letter Q followed by four ___ letters", answer: "silent" },
  { id: "lang-04", category: "language", text: "A pangram is a sentence that contains every ___ of the alphabet", answer: "letter" },
  { id: "lang-05", category: "language", text: "The fear of long words is called ___", answer: "hippopotomonstrosesquippedaliophobia" },
  { id: "lang-06", category: "language", text: "The symbol & was once the ___ letter of the alphabet", answer: "27th" },
  { id: "lang-07", category: "language", text: "The word 'nerd' was first coined by ___", answer: "Dr. Seuss" },
  { id: "lang-08", category: "language", text: "There is a word that means the day after ___: overmorrow", answer: "tomorrow" },
  { id: "lang-09", category: "language", text: "The plastic tip at the end of a shoelace is called an ___", answer: "aglet" },
  { id: "lang-10", category: "language", text: "The space between your eyebrows is called the ___", answer: "glabella" },
  { id: "lang-11", category: "language", text: "Shakespeare invented the word ___", answer: "assassination" },
  { id: "lang-12", category: "language", text: "The opposite of déjà vu is called ___", answer: "jamais vu" },
  { id: "lang-13", category: "language", text: "The metal part of a pencil that holds the eraser is called a ___", answer: "ferrule" },
  { id: "lang-14", category: "language", text: "A person who collects ties is called a ___", answer: "grabatologist" },
  { id: "lang-15", category: "language", text: "The infinity symbol is called a ___", answer: "lemniscate" },

  // ── Body ────────────────────────────────────────────────────────────
  { id: "body-01", category: "body", text: "Humans share about 60% of their DNA with ___", answer: "bananas" },
  { id: "body-02", category: "body", text: "Your stomach gets a completely new lining every ___ days", answer: "three to four" },
  { id: "body-03", category: "body", text: "The human body produces about ___ liters of saliva per day", answer: "one" },
  { id: "body-04", category: "body", text: "The strongest muscle in the human body is the ___", answer: "masseter (jaw muscle)" },
  { id: "body-05", category: "body", text: "Your bones are about ___ times stronger than concrete", answer: "four" },
  { id: "body-06", category: "body", text: "The average person walks the equivalent of ___ times around the world in their lifetime", answer: "five" },
  { id: "body-07", category: "body", text: "Humans are the only animals that produce emotional ___", answer: "tears" },
  { id: "body-08", category: "body", text: "You are taller in the ___ than in the evening", answer: "morning" },
  { id: "body-09", category: "body", text: "The human brain is about ___% fat", answer: "60" },
  { id: "body-10", category: "body", text: "Babies are born with about ___ bones, but adults have only 206", answer: "300" },
  { id: "body-11", category: "body", text: "The only muscle in your body that never tires is your ___", answer: "heart" },
  { id: "body-12", category: "body", text: "Your nose can remember ___ different smells", answer: "50,000" },
  { id: "body-13", category: "body", text: "Humans glow in the dark but the light is ___ times weaker than what the eye can see", answer: "1,000" },
  { id: "body-14", category: "body", text: "The only part of the body that has no blood supply is the ___", answer: "cornea" },
  { id: "body-15", category: "body", text: "Your ___ is the only organ that can regenerate itself", answer: "liver" },

  // ── Inventions ──────────────────────────────────────────────────────
  { id: "inv-01", category: "inventions", text: "Bubble wrap was originally invented to be used as ___", answer: "wallpaper" },
  { id: "inv-02", category: "inventions", text: "Play-Doh was originally used as ___", answer: "wallpaper cleaner" },
  { id: "inv-03", category: "inventions", text: "The microwave was invented after a researcher walked past radar and a ___ melted in his pocket", answer: "chocolate bar" },
  { id: "inv-04", category: "inventions", text: "Coca-Cola was originally ___ colored", answer: "green" },
  { id: "inv-05", category: "inventions", text: "The first computer bug was an actual ___ stuck in a computer", answer: "moth" },
  { id: "inv-06", category: "inventions", text: "Kleenex tissues were originally used as ___ filters in gas masks", answer: "air" },
  { id: "inv-07", category: "inventions", text: "The chainsaw was originally invented for helping with ___", answer: "childbirth" },
  { id: "inv-08", category: "inventions", text: "Listerine was originally marketed as a ___", answer: "floor cleaner" },
  { id: "inv-09", category: "inventions", text: "The can opener was invented ___ years after the can", answer: "48" },
  { id: "inv-10", category: "inventions", text: "Super Glue was discovered by ___ while trying to make clear plastic gun sights", answer: "accident" },
  { id: "inv-11", category: "inventions", text: "The inventor of the fire hydrant is unknown because the patent was destroyed in a ___", answer: "fire" },
  { id: "inv-12", category: "inventions", text: "Velcro was inspired by ___ sticking to a dog's fur", answer: "burrs" },
  { id: "inv-13", category: "inventions", text: "The first alarm clock could only ring at ___", answer: "4 AM" },
  { id: "inv-14", category: "inventions", text: "Post-it Notes were invented because a ___ at 3M kept falling out of his hymnal", answer: "bookmark" },
  { id: "inv-15", category: "inventions", text: "Matches were invented ___ the lighter", answer: "after" },

  // ── Sports ──────────────────────────────────────────────────────────
  { id: "spo-01", category: "sports", text: "Golf balls have an average of ___ dimples", answer: "336" },
  { id: "spo-02", category: "sports", text: "A baseball has exactly ___ stitches", answer: "108" },
  { id: "spo-03", category: "sports", text: "The Olympic flag's five rings represent the five inhabited ___", answer: "continents" },
  { id: "spo-04", category: "sports", text: "Tennis players are not allowed to ___ during a match at Wimbledon", answer: "swear" },
  { id: "spo-05", category: "sports", text: "In professional baseball, the average lifespan of a ball is ___ pitches", answer: "seven" },
  { id: "spo-06", category: "sports", text: "The only sport to have been played on the Moon is ___", answer: "golf" },
  { id: "spo-07", category: "sports", text: "A regulation basketball has exactly ___ panels", answer: "eight" },
  { id: "spo-08", category: "sports", text: "The longest tennis match in history lasted ___ hours", answer: "11" },
  { id: "spo-09", category: "sports", text: "In competitive swimming, a ___ start is faster than diving in from the block in backstroke", answer: "wall push" },
  { id: "spo-10", category: "sports", text: "The first Olympic games featured only one event: a ___ race", answer: "foot" },
  { id: "spo-11", category: "sports", text: "Michael Jordan was cut from his high school ___ team", answer: "basketball" },
  { id: "spo-12", category: "sports", text: "The Stanley Cup has been to the bottom of a ___", answer: "swimming pool" },
  { id: "spo-13", category: "sports", text: "Tug-of-war was an Olympic sport until ___", answer: "1920" },

  // ── Weird Laws & Places ─────────────────────────────────────────────
  { id: "law-01", category: "weird laws", text: "In Switzerland, it's illegal to own just one ___", answer: "guinea pig" },
  { id: "law-02", category: "weird laws", text: "In France, it's illegal to name a pig ___", answer: "Napoleon" },
  { id: "law-03", category: "weird laws", text: "In Ohio, it's illegal to get a ___ drunk", answer: "fish" },
  { id: "law-04", category: "weird laws", text: "In Scotland, it's illegal to be ___ in charge of a cow", answer: "drunk" },
  { id: "law-05", category: "weird laws", text: "In England, it's illegal to die in the ___", answer: "Houses of Parliament" },
  { id: "law-06", category: "weird laws", text: "In Japan, there is a museum dedicated entirely to ___", answer: "rocks that look like faces" },
  { id: "law-07", category: "weird laws", text: "In Sweden, it's a tradition to watch ___ on TV every Christmas Eve", answer: "Donald Duck" },
  { id: "law-08", category: "weird laws", text: "There's a town in Canada where doors are left unlocked in case someone needs to escape from ___", answer: "polar bears" },
  { id: "law-09", category: "weird laws", text: "In Victoria, Australia, only a licensed ___ can change a light bulb", answer: "electrician" },
  { id: "law-10", category: "weird laws", text: "In Singapore, selling ___ has been illegal since 1992", answer: "chewing gum" },
  { id: "law-11", category: "weird laws", text: "In Arizona, donkeys cannot sleep in ___", answer: "bathtubs" },
  { id: "law-12", category: "weird laws", text: "In Thailand, it's illegal to step on ___", answer: "money" },
];

export function selectFacts(
  count: number,
  usedIds: string[],
): { facts: FibFact[]; newUsedIds: string[] } {
  const usedSet = new Set(usedIds);
  const available = FACTS.filter((f) => !usedSet.has(f.id));

  const pool = available.length >= count ? available : [...FACTS];

  const shuffled = pool.sort(() => Math.random() - 0.5);
  const selected = shuffled.slice(0, count);

  return {
    facts: selected,
    newUsedIds: [...usedIds, ...selected.map((f) => f.id)],
  };
}
