import type { Prompt } from "./types";

const PROMPTS: Prompt[] = [
  // ── Food & Drink ──────────────────────────────────────────────────
  { id: "food-01", category: "food", text: "The worst thing to put on a birthday cake: ___" },
  { id: "food-02", category: "food", text: "A restaurant name that would guarantee zero customers" },
  { id: "food-03", category: "food", text: "The secret ingredient grandma puts in everything: ___" },
  { id: "food-04", category: "food", text: "What a five-star chef whispers to each plate before serving it" },
  { id: "food-05", category: "food", text: "The worst flavor of ice cream: ___" },
  { id: "food-06", category: "food", text: "Something you should never deep fry, but someone definitely has" },
  { id: "food-07", category: "food", text: "The real reason your coworker microwaves fish in the office" },
  { id: "food-08", category: "food", text: "A pizza topping that should be illegal: ___" },
  { id: "food-09", category: "food", text: "What a hot dog thinks about right before being eaten" },
  { id: "food-10", category: "food", text: "The worst cereal mascot slogan: ___" },
  { id: "food-11", category: "food", text: "A new energy drink flavor that nobody asked for: ___" },
  { id: "food-12", category: "food", text: "What vegans secretly dream about at night" },
  { id: "food-13", category: "food", text: "The worst thing to bring to a potluck: ___" },
  { id: "food-14", category: "food", text: "Something that sounds like a cocktail but is actually a punishment" },
  { id: "food-15", category: "food", text: "A food truck name that would make people walk the other way" },
  { id: "food-16", category: "food", text: "What your stomach says to you at 2 AM" },
  { id: "food-17", category: "food", text: "The worst cooking show title: ___" },
  { id: "food-18", category: "food", text: "An honest slogan for fast food: ___" },
  { id: "food-19", category: "food", text: "Something you should never put in a smoothie: ___" },
  { id: "food-20", category: "food", text: "The real reason people eat gas station sushi" },
  { id: "food-21", category: "food", text: "A sandwich ingredient that would ruin any friendship" },
  { id: "food-22", category: "food", text: "What the last french fry at the bottom of the bag is thinking" },
  { id: "food-23", category: "food", text: "The worst name for a fancy wine: ___" },
  { id: "food-24", category: "food", text: "Something that would make Gordon Ramsay cry" },
  { id: "food-25", category: "food", text: "A breakfast food that has no business being eaten before noon" },

  // ── Relationships & Dating ────────────────────────────────────────
  { id: "rel-01", category: "relationships", text: "The worst thing to say on a first date: ___" },
  { id: "rel-02", category: "relationships", text: "A dating app bio that would get zero matches" },
  { id: "rel-03", category: "relationships", text: "The worst way to propose to someone" },
  { id: "rel-04", category: "relationships", text: "Something your partner does that you pretend not to notice" },
  { id: "rel-05", category: "relationships", text: "A romantic gesture that would definitely backfire" },
  { id: "rel-06", category: "relationships", text: "The worst pet name for your significant other: ___" },
  { id: "rel-07", category: "relationships", text: "What your ex is probably doing right now" },
  { id: "rel-08", category: "relationships", text: "The worst way to break up with someone" },
  { id: "rel-09", category: "relationships", text: "A red flag that people somehow ignore: ___" },
  { id: "rel-10", category: "relationships", text: "The worst wedding vow: ___" },
  { id: "rel-11", category: "relationships", text: "Something that sounds romantic but is actually creepy" },
  { id: "rel-12", category: "relationships", text: "A pick-up line that has never worked in human history" },
  { id: "rel-13", category: "relationships", text: "The worst couple's Halloween costume: ___" },
  { id: "rel-14", category: "relationships", text: "What you actually mean when you text 'lol'" },
  { id: "rel-15", category: "relationships", text: "Something you should never reveal until the third date" },
  { id: "rel-16", category: "relationships", text: "The most suspicious thing you could find on a partner's phone" },
  { id: "rel-17", category: "relationships", text: "A terrible place to take someone on a first date" },
  { id: "rel-18", category: "relationships", text: "The worst relationship advice you could give: ___" },
  { id: "rel-19", category: "relationships", text: "Something you should never say during an argument" },
  { id: "rel-20", category: "relationships", text: "A Valentine's Day gift that says 'I forgot'" },
  { id: "rel-21", category: "relationships", text: "The worst way to tell someone you love them" },
  { id: "rel-22", category: "relationships", text: "What your dating profile would say if it were brutally honest" },
  { id: "rel-23", category: "relationships", text: "A love song title that would never be a hit: ___" },
  { id: "rel-24", category: "relationships", text: "The worst double date activity" },
  { id: "rel-25", category: "relationships", text: "Something couples fight about that seems ridiculous to everyone else" },

  // ── Work & Career ─────────────────────────────────────────────────
  { id: "work-01", category: "work", text: "Something you should never say in a job interview: ___" },
  { id: "work-02", category: "work", text: "The worst way to quit your job" },
  { id: "work-03", category: "work", text: "What your boss actually does in their office all day" },
  { id: "work-04", category: "work", text: "A meeting that could have been an email about: ___" },
  { id: "work-05", category: "work", text: "The worst thing to put on a résumé: ___" },
  { id: "work-06", category: "work", text: "An honest out-of-office reply: ___" },
  { id: "work-07", category: "work", text: "Something that would get you fired on day one" },
  { id: "work-08", category: "work", text: "The worst career advice ever given: ___" },
  { id: "work-09", category: "work", text: "What everyone is actually thinking during a team-building exercise" },
  { id: "work-10", category: "work", text: "A job title that sounds made up but someone probably has" },
  { id: "work-11", category: "work", text: "The worst thing to say during a performance review" },
  { id: "work-12", category: "work", text: "Something you'd find in the world's worst employee handbook" },
  { id: "work-13", category: "work", text: "What people really mean when they say 'per my last email'" },
  { id: "work-14", category: "work", text: "The worst reason to call in sick: ___" },
  { id: "work-15", category: "work", text: "Something you should never do on a Zoom call" },
  { id: "work-16", category: "work", text: "A corporate slogan that's accidentally honest: ___" },
  { id: "work-17", category: "work", text: "The worst office perk a company could offer" },
  { id: "work-18", category: "work", text: "What the intern is really thinking" },
  { id: "work-19", category: "work", text: "Something you'd find in the break room fridge that's been there too long" },
  { id: "work-20", category: "work", text: "The worst LinkedIn post: ___" },
  { id: "work-21", category: "work", text: "An email subject line that makes everyone panic" },
  { id: "work-22", category: "work", text: "Something no one has ever said sincerely at work" },
  { id: "work-23", category: "work", text: "The worst thing to overhear your boss say" },
  { id: "work-24", category: "work", text: "A terrible company name for a startup: ___" },
  { id: "work-25", category: "work", text: "What people actually do during 'working from home'" },

  // ── Pop Culture & Entertainment ───────────────────────────────────
  { id: "pop-01", category: "pop-culture", text: "A movie sequel nobody asked for: ___" },
  { id: "pop-02", category: "pop-culture", text: "The worst superpower to have" },
  { id: "pop-03", category: "pop-culture", text: "Something a Disney villain would put on their dating profile" },
  { id: "pop-04", category: "pop-culture", text: "A rejected title for a famous movie: ___" },
  { id: "pop-05", category: "pop-culture", text: "The worst reality TV show concept: ___" },
  { id: "pop-06", category: "pop-culture", text: "What a superhero says to their therapist" },
  { id: "pop-07", category: "pop-culture", text: "A video game that would be terrible to play in real life" },
  { id: "pop-08", category: "pop-culture", text: "The worst theme for a music festival: ___" },
  { id: "pop-09", category: "pop-culture", text: "Something you'd find in a celebrity's junk drawer" },
  { id: "pop-10", category: "pop-culture", text: "A band name that would never make it: ___" },
  { id: "pop-11", category: "pop-culture", text: "What Darth Vader says when he stubs his toe" },
  { id: "pop-12", category: "pop-culture", text: "The worst plot twist in a movie: ___" },
  { id: "pop-13", category: "pop-culture", text: "A song that should never be played at a funeral" },
  { id: "pop-14", category: "pop-culture", text: "Something a villain would never admit publicly" },
  { id: "pop-15", category: "pop-culture", text: "The worst thing to yell during a movie theater" },
  { id: "pop-16", category: "pop-culture", text: "A Netflix category that doesn't exist but should: ___" },
  { id: "pop-17", category: "pop-culture", text: "The worst celebrity autobiography title: ___" },
  { id: "pop-18", category: "pop-culture", text: "Something you'd see in a really low-budget superhero movie" },
  { id: "pop-19", category: "pop-culture", text: "The worst song to play at a wedding: ___" },
  { id: "pop-20", category: "pop-culture", text: "What Harry Potter would major in at a normal college" },
  { id: "pop-21", category: "pop-culture", text: "A terrible spinoff show idea: ___" },
  { id: "pop-22", category: "pop-culture", text: "The worst thing to say when meeting a celebrity" },
  { id: "pop-23", category: "pop-culture", text: "A Broadway musical that should never exist: ___" },
  { id: "pop-24", category: "pop-culture", text: "Something every movie gets wrong about real life" },
  { id: "pop-25", category: "pop-culture", text: "The worst catchphrase for an action hero: ___" },

  // ── Animals ───────────────────────────────────────────────────────
  { id: "anim-01", category: "animals", text: "What's the real reason dogs hate the mailman?" },
  { id: "anim-02", category: "animals", text: "Something a cat would say if it could talk" },
  { id: "anim-03", category: "animals", text: "The worst animal to have as a roommate" },
  { id: "anim-04", category: "animals", text: "What a goldfish thinks about all day" },
  { id: "anim-05", category: "animals", text: "An animal that would make the worst therapist" },
  { id: "anim-06", category: "animals", text: "What a pigeon's internal monologue sounds like" },
  { id: "anim-07", category: "animals", text: "The worst name for a pet: ___" },
  { id: "anim-08", category: "animals", text: "Something a dog would post on social media" },
  { id: "anim-09", category: "animals", text: "What squirrels are really planning" },
  { id: "anim-10", category: "animals", text: "An animal that definitely has a secret double life" },
  { id: "anim-11", category: "animals", text: "The worst animal to bring to show-and-tell" },
  { id: "anim-12", category: "animals", text: "What a parrot has definitely overheard and repeated at the worst time" },
  { id: "anim-13", category: "animals", text: "A nature documentary title that would never air: ___" },
  { id: "anim-14", category: "animals", text: "Something you'd see on an animal's résumé" },
  { id: "anim-15", category: "animals", text: "The worst thing to discover your pet has been doing while you're at work" },
  { id: "anim-16", category: "animals", text: "What a mosquito's Yelp review of your blood would say" },
  { id: "anim-17", category: "animals", text: "An animal that would win a talent show, and what its talent is" },
  { id: "anim-18", category: "animals", text: "The worst animal-themed restaurant: ___" },
  { id: "anim-19", category: "animals", text: "What dolphins actually talk about" },
  { id: "anim-20", category: "animals", text: "A pet's brutally honest Yelp review of its owner" },

  // ── Technology & Internet ─────────────────────────────────────────
  { id: "tech-01", category: "tech", text: "The worst app idea: ___" },
  { id: "tech-02", category: "tech", text: "Something Siri says when no one is listening" },
  { id: "tech-03", category: "tech", text: "The worst Wi-Fi network name you've ever seen: ___" },
  { id: "tech-04", category: "tech", text: "What your phone would say if it could judge you" },
  { id: "tech-05", category: "tech", text: "A social media platform that should never exist: ___" },
  { id: "tech-06", category: "tech", text: "The worst password hint: ___" },
  { id: "tech-07", category: "tech", text: "Something that would make a robot quit its job" },
  { id: "tech-08", category: "tech", text: "What your search history would say about you in court" },
  { id: "tech-09", category: "tech", text: "An AI feature nobody wants: ___" },
  { id: "tech-10", category: "tech", text: "The worst autocorrect fail: ___" },
  { id: "tech-11", category: "tech", text: "What your smart fridge thinks of your eating habits" },
  { id: "tech-12", category: "tech", text: "A tech startup pitch that would never get funded" },
  { id: "tech-13", category: "tech", text: "The worst notification to receive at 3 AM: ___" },
  { id: "tech-14", category: "tech", text: "What a printer is actually thinking when it jams" },
  { id: "tech-15", category: "tech", text: "Something that would break the internet: ___" },
  { id: "tech-16", category: "tech", text: "The worst thing to accidentally send to a group chat" },
  { id: "tech-17", category: "tech", text: "A website that definitely shouldn't exist: ___" },
  { id: "tech-18", category: "tech", text: "What your GPS really wants to say to you" },
  { id: "tech-19", category: "tech", text: "The worst thing to google on a work computer" },
  { id: "tech-20", category: "tech", text: "An honest terms-and-conditions clause: ___" },
  { id: "tech-21", category: "tech", text: "What robots will make fun of humans for someday" },
  { id: "tech-22", category: "tech", text: "The worst use for a drone: ___" },
  { id: "tech-23", category: "tech", text: "What your Roomba thinks about while cleaning" },
  { id: "tech-24", category: "tech", text: "A feature that would make a phone completely useless" },
  { id: "tech-25", category: "tech", text: "Something you should never post on the internet" },

  // ── Hypothetical & Weird ──────────────────────────────────────────
  { id: "hypo-01", category: "hypothetical", text: "If aliens landed and asked one question about humans, it would be: ___" },
  { id: "hypo-02", category: "hypothetical", text: "The worst thing to find in a time capsule from 2005" },
  { id: "hypo-03", category: "hypothetical", text: "Something you'd never want to hear a dentist say" },
  { id: "hypo-04", category: "hypothetical", text: "If you could add one rule to any sport, what would it be?" },
  { id: "hypo-05", category: "hypothetical", text: "The worst fortune cookie message: ___" },
  { id: "hypo-06", category: "hypothetical", text: "Something a ghost would complain about" },
  { id: "hypo-07", category: "hypothetical", text: "The worst thing to discover is alive" },
  { id: "hypo-08", category: "hypothetical", text: "A law that would make everyone's life slightly worse" },
  { id: "hypo-09", category: "hypothetical", text: "Something you should never whisper: ___" },
  { id: "hypo-10", category: "hypothetical", text: "The worst thing to find under your bed" },
  { id: "hypo-11", category: "hypothetical", text: "If your life had a loading screen, what tip would it show?" },
  { id: "hypo-12", category: "hypothetical", text: "The worst thing to hear on an airplane intercom: ___" },
  { id: "hypo-13", category: "hypothetical", text: "Something that should be socially acceptable but isn't" },
  { id: "hypo-14", category: "hypothetical", text: "The worst thing to find in your Halloween candy" },
  { id: "hypo-15", category: "hypothetical", text: "If you could rename any country, what would you call it?" },
  { id: "hypo-16", category: "hypothetical", text: "Something a time traveler from the future would warn us about" },
  { id: "hypo-17", category: "hypothetical", text: "The worst thing to yell in a library" },
  { id: "hypo-18", category: "hypothetical", text: "Something you would never want to become sentient" },
  { id: "hypo-19", category: "hypothetical", text: "A terrible wish to waste on a genie" },
  { id: "hypo-20", category: "hypothetical", text: "The worst secret a magician is hiding" },
  { id: "hypo-21", category: "hypothetical", text: "Something that would happen if gravity turned off for 10 seconds" },
  { id: "hypo-22", category: "hypothetical", text: "The worst thing to put in a piñata: ___" },
  { id: "hypo-23", category: "hypothetical", text: "A terrible new holiday and how you'd celebrate it" },
  { id: "hypo-24", category: "hypothetical", text: "Something you should never say to a wizard" },
  { id: "hypo-25", category: "hypothetical", text: "The worst thing to be allergic to: ___" },
  { id: "hypo-26", category: "hypothetical", text: "Something that would be terrifying if it were 10x bigger" },
  { id: "hypo-27", category: "hypothetical", text: "The worst new Olympic sport: ___" },
  { id: "hypo-28", category: "hypothetical", text: "What the Mona Lisa is actually thinking" },
  { id: "hypo-29", category: "hypothetical", text: "A terrible thing to write on a bathroom wall" },
  { id: "hypo-30", category: "hypothetical", text: "The worst thing to say when entering a room full of strangers" },

  // ── Family & Home ─────────────────────────────────────────────────
  { id: "fam-01", category: "family", text: "The worst thing a parent could name their kid: ___" },
  { id: "fam-02", category: "family", text: "Something your mom would be horrified to learn you did" },
  { id: "fam-03", category: "family", text: "The worst advice your dad ever gave you: ___" },
  { id: "fam-04", category: "family", text: "Something you should never say at Thanksgiving dinner" },
  { id: "fam-05", category: "family", text: "What your house would say if it could talk" },
  { id: "fam-06", category: "family", text: "The worst family tradition: ___" },
  { id: "fam-07", category: "family", text: "Something your sibling did that you'll never let them forget" },
  { id: "fam-08", category: "family", text: "The worst housewarming gift: ___" },
  { id: "fam-09", category: "family", text: "What the junk drawer would say at its intervention" },
  { id: "fam-10", category: "family", text: "Something that would make a babysitter quit immediately" },
  { id: "fam-11", category: "family", text: "The worst thing to write in a holiday card: ___" },
  { id: "fam-12", category: "family", text: "Something no parent has ever been proud of their child for doing" },
  { id: "fam-13", category: "family", text: "The worst family vacation destination: ___" },
  { id: "fam-14", category: "family", text: "Something you'd find in a toddler's pocket" },
  { id: "fam-15", category: "family", text: "A lie every parent tells: ___" },
  { id: "fam-16", category: "family", text: "The worst thing to put on a family Christmas letter" },
  { id: "fam-17", category: "family", text: "What your furniture thinks about you" },
  { id: "fam-18", category: "family", text: "Something that would ruin any family photo" },
  { id: "fam-19", category: "family", text: "The worst bedtime story for kids: ___" },
  { id: "fam-20", category: "family", text: "Something every grandparent exaggerates about" },

  // ── School & Education ────────────────────────────────────────────
  { id: "school-01", category: "school", text: "The worst excuse for not doing your homework: ___" },
  { id: "school-02", category: "school", text: "Something a teacher has definitely said behind closed doors" },
  { id: "school-03", category: "school", text: "The worst school mascot: ___" },
  { id: "school-04", category: "school", text: "Something you should never write in a college essay" },
  { id: "school-05", category: "school", text: "The worst field trip destination: ___" },
  { id: "school-06", category: "school", text: "What students actually learn in school" },
  { id: "school-07", category: "school", text: "The worst class to offer in college: ___" },
  { id: "school-08", category: "school", text: "Something you should never do during a final exam" },
  { id: "school-09", category: "school", text: "The worst yearbook quote: ___" },
  { id: "school-10", category: "school", text: "Something a principal would never say over the intercom" },
  { id: "school-11", category: "school", text: "The worst thing to bring for show-and-tell" },
  { id: "school-12", category: "school", text: "An honest valedictorian speech would include: ___" },
  { id: "school-13", category: "school", text: "The worst group project partner behavior" },
  { id: "school-14", category: "school", text: "Something that would make a substitute teacher quit" },
  { id: "school-15", category: "school", text: "The worst school lunch item: ___" },
  { id: "school-16", category: "school", text: "What the school janitor has seen and can never unsee" },
  { id: "school-17", category: "school", text: "The worst topic for a science fair project: ___" },
  { id: "school-18", category: "school", text: "Something every student does but no one admits" },
  { id: "school-19", category: "school", text: "The worst prom theme: ___" },
  { id: "school-20", category: "school", text: "A terrible question to ask during a lecture" },

  // ── Sports & Fitness ──────────────────────────────────────────────
  { id: "sport-01", category: "sports", text: "The worst sports commentary: ___" },
  { id: "sport-02", category: "sports", text: "Something you should never yell at a little league game" },
  { id: "sport-03", category: "sports", text: "The worst trophy inscription: ___" },
  { id: "sport-04", category: "sports", text: "A new exercise that would go viral but is completely useless" },
  { id: "sport-05", category: "sports", text: "Something a gym bro says to sound impressive" },
  { id: "sport-06", category: "sports", text: "The worst halftime show performance: ___" },
  { id: "sport-07", category: "sports", text: "What a golf ball thinks during a swing" },
  { id: "sport-08", category: "sports", text: "The worst motivational poster at a gym: ___" },
  { id: "sport-09", category: "sports", text: "Something you should never say to your personal trainer" },
  { id: "sport-10", category: "sports", text: "A sport that would be improved by adding alligators" },
  { id: "sport-11", category: "sports", text: "The worst thing to chant at a sporting event: ___" },
  { id: "sport-12", category: "sports", text: "Something you'd hear in the world's least inspiring locker room speech" },
  { id: "sport-13", category: "sports", text: "The worst name for a sports team: ___" },
  { id: "sport-14", category: "sports", text: "An athlete's honest post-game interview" },
  { id: "sport-15", category: "sports", text: "The worst rule change for any sport: ___" },
  { id: "sport-16", category: "sports", text: "Something you should never do on a yoga mat" },
  { id: "sport-17", category: "sports", text: "The worst fitness influencer tip: ___" },
  { id: "sport-18", category: "sports", text: "What a referee actually wants to say" },
  { id: "sport-19", category: "sports", text: "A sport that should definitely not be televised" },
  { id: "sport-20", category: "sports", text: "The worst thing to write on a marathon sign" },

  // ── Fashion & Appearance ──────────────────────────────────────────
  { id: "fash-01", category: "fashion", text: "The worst fashion trend that keeps coming back: ___" },
  { id: "fash-02", category: "fashion", text: "Something you should never wear to a job interview" },
  { id: "fash-03", category: "fashion", text: "A clothing item that should be banned: ___" },
  { id: "fash-04", category: "fashion", text: "The worst thing a hairdresser could say mid-haircut" },
  { id: "fash-05", category: "fashion", text: "A fashion line designed by someone who's never seen a human body" },
  { id: "fash-06", category: "fashion", text: "Something your mirror would say if it could be honest" },
  { id: "fash-07", category: "fashion", text: "The worst cologne or perfume name: ___" },
  { id: "fash-08", category: "fashion", text: "A new hat style that nobody would ever buy" },
  { id: "fash-09", category: "fashion", text: "The worst thing to hear when trying on clothes: ___" },
  { id: "fash-10", category: "fashion", text: "Something that would never make it onto a runway" },
  { id: "fash-11", category: "fashion", text: "The worst t-shirt slogan: ___" },
  { id: "fash-12", category: "fashion", text: "A tattoo that seemed like a good idea at the time" },
  { id: "fash-13", category: "fashion", text: "The worst thing to wear to a beach: ___" },
  { id: "fash-14", category: "fashion", text: "What your shoes would say about where they've been" },
  { id: "fash-15", category: "fashion", text: "A celebrity fashion brand that would flop: ___" },

  // ── Travel & Places ───────────────────────────────────────────────
  { id: "trav-01", category: "travel", text: "The worst travel souvenir: ___" },
  { id: "trav-02", category: "travel", text: "Something you should never say going through airport security" },
  { id: "trav-03", category: "travel", text: "The worst tourist attraction idea: ___" },
  { id: "trav-04", category: "travel", text: "An honest hotel review" },
  { id: "trav-05", category: "travel", text: "Something that would ruin any road trip" },
  { id: "trav-06", category: "travel", text: "The worst theme park ride: ___" },
  { id: "trav-07", category: "travel", text: "What a hotel pillow has witnessed" },
  { id: "trav-08", category: "travel", text: "The worst thing to forget when traveling: ___" },
  { id: "trav-09", category: "travel", text: "Something that would make an Airbnb review one star" },
  { id: "trav-10", category: "travel", text: "The worst in-flight movie: ___" },
  { id: "trav-11", category: "travel", text: "Something you'd find in the world's worst hotel" },
  { id: "trav-12", category: "travel", text: "A city tour guide's most embarrassing fact about their city" },
  { id: "trav-13", category: "travel", text: "The worst cruise ship activity: ___" },
  { id: "trav-14", category: "travel", text: "Something that would make a flight attendant snap" },
  { id: "trav-15", category: "travel", text: "The worst thing to happen at baggage claim" },

  // ── Social Situations ─────────────────────────────────────────────
  { id: "soc-01", category: "social", text: "The worst thing to say at a funeral: ___" },
  { id: "soc-02", category: "social", text: "Something you should never bring to a house party" },
  { id: "soc-03", category: "social", text: "The worst icebreaker question: ___" },
  { id: "soc-04", category: "social", text: "Something that would immediately clear a room" },
  { id: "soc-05", category: "social", text: "The worst thing to say when meeting your partner's parents" },
  { id: "soc-06", category: "social", text: "A toast that would make everyone uncomfortable" },
  { id: "soc-07", category: "social", text: "Something you should never do at a baby shower" },
  { id: "soc-08", category: "social", text: "The worst way to introduce yourself: ___" },
  { id: "soc-09", category: "social", text: "Something you should never say to a stranger in an elevator" },
  { id: "soc-10", category: "social", text: "The worst thing to do at someone else's wedding" },
  { id: "soc-11", category: "social", text: "Something that would ruin any dinner party" },
  { id: "soc-12", category: "social", text: "The worst thing to say when someone shows you their baby: ___" },
  { id: "soc-13", category: "social", text: "Something you should never admit at a reunion" },
  { id: "soc-14", category: "social", text: "The worst way to respond to 'How are you?'" },
  { id: "soc-15", category: "social", text: "Something you should never say while giving a best man speech" },

  // ── History & Politics ────────────────────────────────────────────
  { id: "hist-01", category: "history", text: "The worst presidential campaign slogan: ___" },
  { id: "hist-02", category: "history", text: "Something a king would never admit to their subjects" },
  { id: "hist-03", category: "history", text: "A historical event that was definitely someone's accident" },
  { id: "hist-04", category: "history", text: "The worst thing to invent: ___" },
  { id: "hist-05", category: "history", text: "Something a pirate captain's crew complains about" },
  { id: "hist-06", category: "history", text: "The worst campaign promise: ___" },
  { id: "hist-07", category: "history", text: "What the person who invented pants was trying to solve" },
  { id: "hist-08", category: "history", text: "The worst amendment to add to the Constitution: ___" },
  { id: "hist-09", category: "history", text: "Something that would be in the museum of bad ideas" },
  { id: "hist-10", category: "history", text: "A monument nobody would visit: ___" },
  { id: "hist-11", category: "history", text: "The worst historical figure to be stuck in an elevator with" },
  { id: "hist-12", category: "history", text: "Something a caveman would be confused by in modern life" },
  { id: "hist-13", category: "history", text: "The worst thing to put on a national flag: ___" },
  { id: "hist-14", category: "history", text: "An honest campaign poster would say: ___" },
  { id: "hist-15", category: "history", text: "Something future historians will judge us for" },

  // ── Health & Body ─────────────────────────────────────────────────
  { id: "health-01", category: "health", text: "The worst thing a doctor could say after looking at your X-ray" },
  { id: "health-02", category: "health", text: "Something you should never admit to your doctor" },
  { id: "health-03", category: "health", text: "The worst wellness trend: ___" },
  { id: "health-04", category: "health", text: "An honest description of what happens at 30: ___" },
  { id: "health-05", category: "health", text: "Something no one talks about but everyone experiences" },
  { id: "health-06", category: "health", text: "The worst thing to say to a dentist while they're working" },
  { id: "health-07", category: "health", text: "A vitamin supplement that definitely doesn't exist: ___" },
  { id: "health-08", category: "health", text: "The worst self-help book title: ___" },
  { id: "health-09", category: "health", text: "Something your body does that it really should apologize for" },
  { id: "health-10", category: "health", text: "The worst reason to go to the emergency room" },

  // ── Miscellaneous ─────────────────────────────────────────────────
  { id: "misc-01", category: "misc", text: "The worst thing to write on a welcome mat: ___" },
  { id: "misc-02", category: "misc", text: "Something that sounds like a compliment but is actually an insult" },
  { id: "misc-03", category: "misc", text: "The worst bumper sticker: ___" },
  { id: "misc-04", category: "misc", text: "Something you should never say to a police officer" },
  { id: "misc-05", category: "misc", text: "The worst life hack: ___" },
  { id: "misc-06", category: "misc", text: "A warning label that shouldn't need to exist but does" },
  { id: "misc-07", category: "misc", text: "The worst thing to teach a parrot to say: ___" },
  { id: "misc-08", category: "misc", text: "Something that would make a terrible alarm clock sound" },
  { id: "misc-09", category: "misc", text: "The worst inspirational quote: ___" },
  { id: "misc-10", category: "misc", text: "Something you'd find in the lost-and-found at a theme park" },
  { id: "misc-11", category: "misc", text: "The worst thing to whisper to someone: ___" },
  { id: "misc-12", category: "misc", text: "Something a fortune teller would never predict" },
  { id: "misc-13", category: "misc", text: "The worst thing to say during an awkward silence" },
  { id: "misc-14", category: "misc", text: "Something that would be confusing to explain to a caveman" },
  { id: "misc-15", category: "misc", text: "The worst thing to discover at the bottom of a swimming pool" },
  { id: "misc-16", category: "misc", text: "A terrible name for a boat: ___" },
  { id: "misc-17", category: "misc", text: "The worst billboard ad: ___" },
  { id: "misc-18", category: "misc", text: "Something you'd never want a mind reader to know" },
  { id: "misc-19", category: "misc", text: "The worst thing to be famous for" },
  { id: "misc-20", category: "misc", text: "Something that exists solely to annoy people" },
];

export function getAllPrompts(): Prompt[] {
  return PROMPTS;
}

export function selectPrompts(
  count: number,
  usedIds: string[],
  extraPrompts: Prompt[] = [],
): Prompt[] {
  const pool = [...PROMPTS, ...extraPrompts];
  const usedSet = new Set(usedIds);
  const available = pool.filter((p) => !usedSet.has(p.id));

  const byCategory = new Map<string, Prompt[]>();
  for (const p of available) {
    const list = byCategory.get(p.category) ?? [];
    list.push(p);
    byCategory.set(p.category, list);
  }

  const selected: Prompt[] = [];
  const categoryCount = new Map<string, number>();

  const shuffled = [...available].sort(() => Math.random() - 0.5);

  for (const prompt of shuffled) {
    if (selected.length >= count) break;

    const catCount = categoryCount.get(prompt.category) ?? 0;
    if (catCount >= 2) continue;

    selected.push(prompt);
    categoryCount.set(prompt.category, catCount + 1);
  }

  if (selected.length < count) {
    for (const prompt of shuffled) {
      if (selected.length >= count) break;
      if (selected.includes(prompt)) continue;
      selected.push(prompt);
    }
  }

  return selected;
}
